server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
logging:
  level:
    root: INFO
    com.ktds: DEBUG
